name: Build

on:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-linux
            os: ubuntu-24.04-arm
          - system: aarch64-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - run: nix build .#default

      - uses: actions/upload-artifact@v7
        with:
          name: stickshift-${{ matrix.system }}
          path: result/bin/stickshift
